# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2026
    customText = ""

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    #emoji    = "🍥"
    subtitle = "Make something new in Mihoyo now"
    avatar   = "img/Avatar.png"

[article]
    headingAnchor = false
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

# 1. 强制 Hugo 在处理头像时不进行中央硬裁切 (fill)，而是完整缩放 (fit)
[imaging.avatar]
    action = "fit"

# 2. 告诉 Stack 主题，不要帮我加任何自定义 CSS 文件的壳，完全走正统通道
[assets]
    customSCSS = "scss/custom.scss"

## Comments
[comments]
    enabled = true
    provider = "giscus"

[comments.giscus]
    repo = "jc-law/HomePage"
    repoId = "R_kgDOSRlAvQ"
    category = "Announcements"
    categoryId = "DIC_kwDOSRlAvc4C8mdP"
    mapping = "pathname"
    strict = 0
    reactionsEnabled = 1
    emitMetadata = 0
    inputPosition = "bottom"
    lightTheme = "light"
    darkTheme = "dark"
    theme = "preferred_color_scheme"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.
